/**
 * Represents an owner
 *
 * @author Lynda Thomas, Chris Loftus and Faisal Rezwan, LOV2
 * @version 3 (20th February 2023)
 */
public class Owner {
    private String name;
    private String phone;


    /**
     * default constructor
     * @param n name of the owner
     * @param p phone number of the owner
     */
    public Owner(String n, String p) {
        name = n;
        phone = p;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public boolean equals(Object obj) { // Robust version generated by IDE
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Owner other = (Owner) obj;
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;
        if (phone == null) {
            if (other.phone != null)
                return false;
        } else if (!phone.equals(other.phone))
            return false;
        return true;
    }


    /**
     * ToString method for the owner class when called
     * @return all information about an owner object.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        return sb.append(name).append(" ").append(phone).toString();
    }

}
